apiVersion: v1
kind: Service
metadata:
  name: hangman-service
spec:
  selector:
    app: hangman
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30143
  type: NodePort